apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/bionic-upgrade-484010-t5/locations/us-central1-c/clusters/autopilot-cluster-2

